# Configuração CircleCI para testes e deploy de projeto Java
version: 2.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      # Etapa opcional para garantir que as dependências estejam instaladas
      - run:
          name: Install dependencies
          command: mvn dependency:go-offline -B
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
            sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Run tests
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '# e.g. ./deploy.sh'  # Substitua por script real de deploy

workflows:
  build-and-test:
    jobs:
      - test-java
    # Descomente o bloco abaixo para ativar o deploy após os testes:
    # - deploy:
    #     requires:
    #       - test-java
